server:
  port: 8088
spring:
  application:
    name: Journal
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 114514
    url: jdbc:mysql://localhost:3306/wiki?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: MyHikariPool
#    name: defaultDataSource
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml



