server:
  port: 8088
spring:
  application:
    name: Wiki
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 114514
    url: jdbc:mysql://localhost:3306/wiki?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: MyHikariPool
springdoc:
  packages-to-scan:
    com.solaluna.wiki.controller
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
logging:
  level:
    com.hexadecimal: debug
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
yukitaka:
  jwt:
    secret: yukitaka1116
    expire: 21600
    header: Authorization